Problem: CI artifacts collection is not uniform
Solution:
- create `ci/collect-artifacts` script;
- call it from both test-boot{1,2} jobs;
- refactor `.gitlab-ci.yml` using YAML anchors.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -50,49 +50,34 @@ test-utils:
   except: [ tags ]
   script: [ ci/test-utils ]
 
+# See https://docs.gitlab.com/ce/ci/yaml/README.html#anchors
+.after_script_template: &after_script_definition
+  - date -u -Isec
+  - cd $WORKSPACE_DIR
+  - /usr/bin/time hare/ci/collect-artifacts
+
+  # Clean up.  This ensures that VMs are destroyed in case of a manual
+  # job restart, when global 'cleanup' stage is not performed.
+  - $M0VG destroy -f || true
+
+.artifacts_template: &artifacts_definition
+  name: "$CI_PROJECT_NAME job $CI_JOB_ID ($CI_JOB_NAME) logs"
+  when: always  # whenever the job has failed or succeeded
+  paths:
+    - ${CI_JOB_NAME}*consul*.log
+    - ${CI_JOB_NAME}*m0reportbug-data.tar.xz
+    # - ${CI_JOB_NAME}*m0reportbug-cores.tar.xz  # XXX too big
+    - ${CI_JOB_NAME}*m0reportbug-traces.tar.xz
+    - ${CI_JOB_NAME}*syslog.log
+
 test-boot1:
   stage: test
   tags: [ m0vg ]
   except: [ tags ]
   variables: { M0VG: m0vg-1node/scripts/m0vg }
   script: [ ci/test-boot1 ]
-
-  after_script:
-    - date -u -Isec
-    - cd $WORKSPACE_DIR
-
-    # Collect syslog.
-    - $M0VG run sudo journalctl --no-pager --full --utc --boot
-                                --output short-precise
-                                > $CI_PROJECT_DIR/${CI_JOB_NAME}_syslog.log
-
-    # Collect Consul logs.
-    - |
-      $M0VG scp cmu:/tmp/consul\*.log $CI_PROJECT_DIR/
-      ( cd $CI_PROJECT_DIR/
-        for f in consul*.log; do mv -v {,${CI_JOB_NAME}_}$f; done )
-
-    # Collect m0reportbug archives.
-    - |
-      $M0VG run sudo /data/mero/utils/m0reportbug
-      $M0VG scp cmu:m0reportbug-\*.tar.xz $CI_PROJECT_DIR/
-      ( cd $CI_PROJECT_DIR/
-        for f in m0reportbug-*.tar.xz; do mv -v {,${CI_JOB_NAME}_}$f; done )
-
-    # Clean up.  This ensures that VMs are destroyed in case of a manual
-    # job restart, when global 'cleanup' stage is not performed.
-    - $M0VG destroy -f || true
-
-  artifacts:
-    name: "$CI_PROJECT_NAME job $CI_JOB_ID ($CI_JOB_NAME) logs"
-    when: always  # whenever the job has failed or succeeded
-    paths:
-      - ${CI_JOB_NAME}_syslog.log
-      - ${CI_JOB_NAME}_m0reportbug-data.tar.xz
-      # - ${CI_JOB_NAME}_m0reportbug-cores.tar.xz  # XXX core files are big
-      - ${CI_JOB_NAME}_m0reportbug-traces.tar.xz
-      - ${CI_JOB_NAME}_consul*.log
-
+  after_script: *after_script_definition
+  artifacts: *artifacts_definition
 
 test-boot2:
   stage: test
@@ -100,52 +85,8 @@ test-boot2:
   except: [ tags ]
   variables: { M0VG: m0vg-2nodes/scripts/m0vg }
   script: [ ci/test-boot2 ]
-
-  after_script:
-    - date -u -Isec
-    - cd $WORKSPACE_DIR
-
-    # Collect syslogs.
-    - |
-      for host in ssu1 ssu2; do
-          $M0VG run --vm $host sudo journalctl \
-              --no-pager --full --utc --boot --output short-precise \
-              > $CI_PROJECT_DIR/${CI_JOB_NAME}_${host}_syslog.log
-      done
-
-    # Collect Consul logs.
-    - |
-      for host in ssu1 ssu2; do
-          $M0VG scp $host:/tmp/consul\*.log $CI_PROJECT_DIR/
-          ( cd $CI_PROJECT_DIR/
-            for f in consul*.log; do mv -v {,${CI_JOB_NAME}_${host}_}$f; done )
-      done
-
-    # Collect m0reportbug archives.
-    - |
-      for host in ssu1 ssu2; do
-          $M0VG run --vm $host sudo /data/mero/utils/m0reportbug
-          $M0VG scp $host:m0reportbug-\*.tar.xz $CI_PROJECT_DIR/
-          ( cd $CI_PROJECT_DIR/
-            for f in m0reportbug-*.tar.xz; do
-                mv -v {,${CI_JOB_NAME}_${host}_}$f
-            done )
-      done
-
-    # Clean up.  This ensures that VMs are destroyed in case of a manual
-    # job restart, when global 'cleanup' stage is not performed.
-    - $M0VG destroy -f || true
-
-  artifacts:
-    name: "$CI_PROJECT_NAME job $CI_JOB_ID ($CI_JOB_NAME) logs"
-    when: always  # whenever the job has failed or succeeded
-    paths:
-      - ${CI_JOB_NAME}_*_syslog.log
-      - ${CI_JOB_NAME}_*_m0reportbug-data.tar.xz
-      # - ${CI_JOB_NAME}_*_m0reportbug-cores.tar.xz  # XXX core files are big
-      - ${CI_JOB_NAME}_*_m0reportbug-traces.tar.xz
-      - ${CI_JOB_NAME}_*_consul*.log
-
+  after_script: *after_script_definition
+  artifacts: *artifacts_definition
 
 # Cleanup ----------------------------------------------------------------- {{{1
 #
