Problem: bootstrap on existing Mero data is needed
After the EES HA failover, we should be able to bootstrap
the cluster on existing Mero data without running m0mkfs.

Solution: add `--mkfs` option to the `bootstrap` script.
By default, no m0mkfs should be done (it wipes away all
user's data in Mero and should be considered a dangerous
operation).

Closes #114.

diff --git a/bootstrap-node b/bootstrap-node
--- a/bootstrap-node
+++ b/bootstrap-node
@@ -3,30 +3,53 @@ set -eu -o pipefail
 # set -x
 export PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}}] '
 
+PROG=${0##*/}
 SRC_DIR="$(dirname $(readlink -f $0))"
-prog=${0##*/}
 
 usage() {
     cat <<EOF
-Usage: $prog { phase1 | phase2 }
+Usage: $PROG [--mkfs] { -p|--phase 1|2 }
 
 Bootstraps single node after consul agent is started.
 
 The required parameter is one of the following:
 
-  phase1 - start confd Mero process(es)
-  phase2 - start ios Mero process(es)
+  --phase 1 - start confd Mero process(es)
+  --phase 2 - start ios Mero process(es)
+
+Options:
+  --mkfs                    Do m0mkfs (WARNING: wipes Mero data).
+  -h, --help                Show this help and exit.
 EOF
 }
 
-case "$*" in
-    phase[12]) ;;
-    *) usage >&2; exit 1;;
-esac
-phase=$1
+do_mkfs=false
+phase=-
+
+TEMP=$(getopt --options hp: \
+              --longoptions help,mkfs,phase: \
+              --name "$PROG" -- "$@" || true)
+
+(($? == 0)) || { usage >&2; exit 1; }
+
+eval set -- "$TEMP"
+while true; do
+    case "$1" in
+        -h|--help)           usage; exit ;;
+        --mkfs)              do_mkfs=true; shift ;;
+        -p|--phase)          phase=$2; shift 2 ;;
+        --)                  shift; break ;;
+        *)                   echo 'getopt: internal error...'; exit 1 ;;
+    esac
+done
+
+[[ $phase =~ ^[12]$ ]] || {
+    usage >&2
+    exit 1
+}
 
 die() {
-    >&2 echo "$prog: $HOSTNAME: $*"
+    >&2 echo "$PROG: $HOSTNAME: $*"
     exit 1
 }
 
@@ -54,13 +77,13 @@ if [[ -n $CONFD_IDs || -n $IOS_IDs ]]; then
     done
 fi
 
-if [[ -n $CONFD_IDs && $phase == phase1 ]]; then
+if [[ -n $CONFD_IDs && $phase == 1 ]]; then
     [[ -f /tmp/confd.xc ]] ||
         die 'Cannot bootstrap a server node without /tmp/confd.xc file'
     sudo mv /tmp/confd.xc /etc/mero/
 fi
 
-if [[ $phase == phase1 ]]; then
+if [[ $phase == 1 ]]; then
     IDs=$CONFD_IDs
 else
     IDs=$IOS_IDs
@@ -68,10 +91,12 @@ fi
 
 for id in $IDs; do
     fid=$(id2fid $id)
-    sudo systemctl start mero-mkfs@$fid
-    touch /tmp/mero-mkfs-pass-$fid
-    # Give time for service check to reset m0mkfs' HA state:
-    # (1s * 2) - time of two checks + 1s. (See check-service.)
-    sleep 3
+    if $do_mkfs; then
+        sudo systemctl start mero-mkfs@$fid
+        touch /tmp/mero-mkfs-pass-$fid
+        # Give time for service check to reset m0mkfs' HA state:
+        # (1s * 2) - time of two checks + 1s. (See check-service.)
+        sleep 3
+    fi
     sudo systemctl start m0d@$fid
 done
