check-confd: Style edits

diff --git a/check-confd b/check-confd
--- a/check-confd
+++ b/check-confd
@@ -2,16 +2,17 @@
 set -eu -o pipefail
 
 #
-# This is the Health Check for the Mero confd service.
+# Health check for the Mero confd service.
 #
-if [ $(consul kv get processes/0x7200000000000001:0x1 | jq '.state' -r) = "M0_CONF_HA_PROCESS_STARTED" ]
-then
-  rm -f /tmp/confd # cleanup after the bootstrap stage
-  exit 0
-else
-  if [ -f /tmp/confd ]; then
-    exit 0 # bootstrap stage
-  else
-    exit 2
-  fi
+
+CONFD_STATE=$(consul kv get processes/0x7200000000000001:0x1 | jq '.state' -r)
+if [[ $CONFD_STATE = 'M0_CONF_HA_PROCESS_STARTED' ]]; then
+    rm -f /tmp/confd  # cleanup after the bootstrap stage
+    exit 0
 fi
+
+if [[ -f /tmp/confd ]]; then
+    exit 0  # confd is still starting
+fi
+
+exit 2
