Fix session leak on RC crash

diff --git a/elect-rc-leader b/elect-rc-leader
--- a/elect-rc-leader
+++ b/elect-rc-leader
@@ -16,32 +16,34 @@ get_session_id() {
   consul kv get -detailed leader | awk '/Session/ {print $2}'
 }
 
-# If there is no session on the leader key - we should cleanup
-# EQ watcher and currently running RC handler before continuing.
-# Otherwise just exit - there is nothing to do.
-SID=$(get_session_id)
-if [ "x$SID" == "x-" ]; then
-  pkill -f -9 proto-rc || true
-else
-  exit 0
-fi
+# If the session is already set - the leader is elected, so
+# there is nothing for us to do.
+get_session_id | grep -q ^- || exit 0
+
+# Cleanup EQ watcher and currently running RC handler (if any).
+pkill -f -9 proto-rc || true
 
 die() {
   echo $1
+  exit 0 # Don't stop the watcher.
+}
+
+PAYLD='{"Name": "leader", "Checks": ["serfHealth", "service:confd"]}'
+RES=`curl -sX PUT -d "$PAYLD" http://localhost:8500/v1/session/create`
+SID=`echo "$RES" | jq -r '.ID' 2>/dev/null` || true
+
+test -n "$SID" || die "Session creation failed: $RES"
+
+clean_exit() {
+  curl -sX PUT http://localhost:8500/v1/session/destroy/$SID &>/dev/null || true
   exit 0
 }
 
-SPAYLD='{"Name": "leader", "Checks": ["serfHealth", "service:confd"]}'
-SRES=`curl -sX PUT -d "$SPAYLD" http://localhost:8500/v1/session/create`
-SID=`echo "$SRES" | jq -r '.ID' 2>/dev/null` || true
-
-test -n "$SID" || die "Session creation failed: $SRES"
-
-# Try to acquire the lock until it's already acquired by someone:
-while get_session_id | grep -q ^- || exit 0; do
+# Try to acquire the lock unless it's already acquired by someone else:
+while get_session_id | grep -q ^- || clean_exit; do
   consul kv put -acquire -session=$SID leader `hostname` 2>/dev/null && break
   sleep 5
 done
 
-# We acquired the lock! Start the EQ watcher.
+# We've got the lock! Start the EQ watcher.
 $HOME/hare/new-rc-leader &
