Problem: update-consul-env to update optional params
update-consul-env script should be able to update optional
consul agent startup parameters (like `-bootstrap-expect 1`
which should be used on one of the cluster nodes only).

Solution: add such support.

diff --git a/update-consul-env b/update-consul-env
--- a/update-consul-env
+++ b/update-consul-env
@@ -1,25 +1,58 @@
 #!/usr/bin/env bash
 set -eu -o pipefail
 
+PROG_NAME=${0##*/}
 SRC_DIR="$(dirname $(readlink -f $0))"
 ENV_FILE=$SRC_DIR/systemd/consul-env
 
 usage() {
-    echo "Usage: ${0##*/} <client|server> <bind_address> <join_address>"
-    echo
-    echo "Updates Consul agent startup parameters at $ENV_FILE."
+    >&2 cat <<EOF
+Usage: ${0##*/} -m|--mode <client|server> -b|--bind <IP>
+                [-j|--join <IP>] [-e|--extra-options <string>]"
+
+Updates Consul agent startup parameters at $ENV_FILE.
+EOF
     exit 1
 }
 
-(( $# < 3 )) && usage
+mode=
+bind_addr=
+join_addr=
+extra_opts=
+
+TEMP=$(getopt --options hm:b:j:e: \
+              --longoptions help,mode:,bind:,join:,extra-options: \
+              --name "$PROG_NAME" -- "$@" || true)
+
+[[ $? -ne 0 ]] && usage
+
+eval set -- "$TEMP"
+
+while true ; do
+    case "$1" in
+        -h|--help)           usage ;;
+        -m|--mode)           mode=$2; shift 2 ;;
+        -b|--bind)           bind_addr=$2; shift 2 ;;
+        -j|--join)           join_addr=$2; shift 2 ;;
+        -e|--extra-options)  extra_opts=$2; shift 2 ;;
+        --)                  shift; break ;;
+        *)                   echo 'getopt: internal error...'; exit 1 ;;
+    esac
+done
+
+[[ -n $mode && -n $bind_addr ]] || usage
 
 sudo rm -rf /tmp/consul
 
-mode=$1
-bind_addr=$2
-join_addr=$3
-
 sed -r -e "s/^(MODE).*/\1=$mode/" \
        -e "s/^(BIND).*/\1=$bind_addr/" \
-       -e "s/^(CLIENT).*/\1=127.0.0.1 $bind_addr/" \
-       -e "s/^(JOIN).*/\1=${join_addr:+-retry-join $join_addr}/" -i $ENV_FILE
+       -e "s/^(CLIENT).*/\1=127.0.0.1 $bind_addr/" -i $ENV_FILE
+
+if [[ -n $join_addr ]]; then
+    sed -r -e "s/^(JOIN).*/\1=${join_addr:+-retry-join $join_addr}/" \
+        -i $ENV_FILE
+fi
+
+if [[ -n $extra_opts ]]; then
+    sed -r "s/^(EXTRA_OPTS).*/\1=$extra_opts/" -i $ENV_FILE
+fi
