EOS-27069: hare does not support multiple network transports
Presently Hare supports just libfabric in Containers. This restricts testing
Hare and Motr using different transports, e.g. lnet.

Solution:
- Update Hare configuration to support multiple transports.

Signed-off-by: Mandar Sawant <mandar.sawant@seagate.com>

diff --git a/utils/hare-node-join b/utils/hare-node-join
--- a/utils/hare-node-join
+++ b/utils/hare-node-join
@@ -42,6 +42,8 @@ Positional arguments:
   --consul-port <port>   Active Consul server port.
 Options:
   -h, --help    Show this help and exit.
+  --xprt        Use given motr transport type to generate corresponding motr
+                endpoints. Supported transport types are lnet and libfab.
 EOF
 }
 
@@ -143,7 +145,7 @@ is_localhost() {
 
 TEMP=$(getopt --options hc: \
               --longoptions help,conf-dir:,consul-addr:,consul-port: \
-              --longoptions mkfs,conf-create,debug \
+              --longoptions mkfs,conf-create,debug,xprt: \
               --name "$PROG" -- "$@" || true)
 
 (($? == 0)) || { usage >&2; exit 1; }
@@ -154,6 +156,7 @@ conf_dir=
 debug_p=false
 conf_create=false
 opt_mkfs=
+xprt='libfab'
 
 while true; do
     case "$1" in
@@ -162,6 +165,7 @@ while true; do
         --consul-addr)  CONSUL_ADDR=$2; shift 2 ;;
         --consul-port)  CONSUL_PORT=$2; shift 2 ;;
         --mkfs)         opt_mkfs=--mkfs; shift ;;
+        --xprt)         xprt=$2; shift 2 ;;
         --conf-create)  conf_create=true; shift ;;
         --)             shift; break ;;
         *)              break ;;
@@ -182,6 +186,7 @@ if sudo systemctl --quiet is-active hare-consul-agent; then
     die 'hare-consul-agent is active ==> cluster is already running'
 fi
 
+[[ $xprt == 'lnet' ]] || [[ $xprt == 'libfab' ]] || die "Invalid transport type $xprt"
 
 if [[ -z $conf_dir ]]; then
     conf_dir=/var/lib/hare
@@ -282,7 +287,7 @@ done
 
 if $conf_create; then
     say 'Updating Consul agents configs from the KV store...'
-    update-consul-conf &
+    update-consul-conf --xprt $xprt &
     pids=($!)
     echo ' OK'
 fi
@@ -318,7 +323,7 @@ start_motr() {
 
     say "Starting Motr ($phase, $op)..."
     [[ $op == 'mkfs' ]] && op='--mkfs-only' || op=
-    bootstrap-node $op --phase $phase &
+    bootstrap-node $op --phase $phase --xprt $xprt &
     pids=($!)
     wait4 ${pids[@]}
     echo ' OK'
@@ -340,11 +345,11 @@ bootstrap_nodes phase1
 # Start ioservices
 bootstrap_nodes phase2
 
-. update-consul-conf --dry-run  # import S3_IDs
+. update-consul-conf --dry-run --xprt $xprt # import S3_IDs
 if [[ -n $S3_IDs ]]; then
     # Now the 3rd phase (s3servers).
     say 'Starting S3 servers (phase3)...'
-    bootstrap-node --phase phase3 &
+    bootstrap-node --phase phase3 --xprt $xprt &
     pids=($!)
     wait4 ${pids[@]}
     echo ' OK'
diff --git a/utils/hare-start b/utils/hare-start
--- a/utils/hare-start
+++ b/utils/hare-start
@@ -38,6 +38,8 @@ Starts Hare and Motr services on local or all the nodes in the cluster.
 
 Options:
   --node       Starts hare and motr services on current node only.
+  --xprt       Use given motr transport type to generate corresponding motr
+               process endpoints. Supported transport types are lnet and libfab.
   -h, --help   Shows this help and exit.
 EOF
 
@@ -45,18 +47,20 @@ EOF
 }
 
 TEMP=$(getopt --options h \
-              --longoptions help,node \
+              --longoptions help,node,xprt: \
               --name "$PROG" -- "$@" || true)
 
 eval set -- "$TEMP"
 
 conf_dir=/var/lib/hare
 node=false
+xprt='lnet'
 
 while true; do
     case "$1" in
         -h|--help)           usage ;;
         --node)              node=true; shift ;;
+        --xprt)              xprt=$2; shift 2 ;;
         --)                  shift; break ;;
         *)                   break ;;
     esac
@@ -70,9 +74,11 @@ if  hctl status > /dev/null 2>&1; then
     die 'Cluster is up and running.'
 fi
 
+[[ $xprt == 'lnet' ]] || [[ $xprt == 'libfab' ]] || die "Invalid transport type $xprt"
+
 if $node; then
     start-node
 else
-    hctl bootstrap -c $conf_dir
+    hctl bootstrap -c $conf_dir --xprt $xprt
 fi
 
diff --git a/utils/start-node b/utils/start-node
--- a/utils/start-node
+++ b/utils/start-node
@@ -38,6 +38,50 @@ is_server_node() {
     get_server_nodes | grep -w $(node-name) > /dev/null
 }
 
+usage() {
+    cat <<EOF
+Usage: $PROG [<option>]...
+
+Starts Hare and Motr services on local node.
+
+Options:
+  --xprt       Use given motr transport type to generate corresponding motr
+               process endpoints. Supported transport types are lnet and libfab.
+  -h, --help   Shows this help and exit.
+EOF
+
+    exit 1;
+}
+
+TEMP=$(getopt --options h \
+              --longoptions help,xprt: \
+              --name "$PROG" -- "$@" || true)
+
+eval set -- "$TEMP"
+
+conf_dir=/var/lib/hare
+xprt='lnet'
+
+while true; do
+    case "$1" in
+        -h|--help)           usage ;;
+        --xprt)              xprt=$2; shift 2 ;;
+        --)                  shift; break ;;
+        *)                   break ;;
+    esac
+done
+
+if ! [[ -d $conf_dir ]]; then
+    die 'Cluster is not configured on this node.'
+fi
+
+if  hctl status > /dev/null 2>&1; then
+    die 'Cluster is up and running.'
+fi
+
+[[ $xprt == 'lnet' ]] || [[ $xprt == 'libfab' ]] || die "Invalid transport type $xprt"
+
+
 if sudo systemctl --quiet is-active hare-consul-agent; then
     die 'hare-consul-agent is active ==> cluster is already running'
 fi
@@ -57,16 +101,16 @@ echo ' OK'
 
 if is_server_node; then
     # Starting phase 1 (confd servers)
-    start_motr m0d phase1
+    start_motr m0d phase1 $xprt
 fi
 
 # Starting phase 2 (ios)
-start_motr m0d phase2
+start_motr m0d phase2 $xprt
 
-. update-consul-conf --dry-run  # import S3_IDs
+. update-consul-conf --dry-run  --xprt $xprt # import S3_IDs
 if [[ -n $S3_IDs ]]; then
     # Starting phase 3 (s3servers).
-    start_s3server
+    start_s3server $xprt
 fi
 
 say 'Checking health of services...'
