hare-bootstrap: fix consul leader check (#1858)
With bash `set -o pipefail`, the following construction may
give a false negative status result:

    cmd | grep -q something

if the `cmd` returns multiple lines.

The reason is that the grep command with `-q` option finishes
immediately as soon as it finds `something`.  But in case of
multiple lines output from `cmd`, the latter might get killed
by SIGPIPE (because grep has already exited). So the resulting
status of the whole command will be 141 instead of 0.

This is exactly what sometimes happens when we check the status
of internal Consul leader on bootstrap.  On slow virtual machines
(like arm64 in QEMU) the check in the loop might take a lot of
time returning false negative results, until it happens that
the grep process is still running, and the pipe is not closed,
by the time `cmd` finishes outputting into the pipe.

Solution: use the following construction instead:

    grep -q something <<< $(cmd)

Signed-off-by: Andriy Tkachuk <andriy.tkachuk@seagate.com>
(cherry picked from commit 907a9baa4c98a89a81f0b4c6fa66f296ed89c26e)

diff --git a/utils/hare-bootstrap b/utils/hare-bootstrap
--- a/utils/hare-bootstrap
+++ b/utils/hare-bootstrap
@@ -352,7 +352,13 @@ sudo systemctl start hare-consul-agent
 
 # Wait for Consul's internal leader to be ready.
 # (Until then the KV store won't be accessible.)
-while ! consul info 2>/dev/null | grep -q 'leader.*true'; do
+#
+# Note: the code is written this way without the pipe here on purpose.
+# With bash `set -o pipefail' setting (see above in the begginning),
+# it will return the status of the 1st failed command in the pipe,
+# which will be not of grep, but of consul, who will fail by SIGPIPE,
+# when `grep -q' process finish before consul is finished.
+while ! grep -q 'leader *= *true' <<< "$(consul info 2>/dev/null)"; do
     sleep 1
     echo -n '.'
 done
